# Generated by Django 2.1.7 on 2019-04-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190401_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='peticiones_count',
        ),
    ]
