# Generated by Django 2.1.7 on 2019-04-12 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20190410_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
    ]
