# Generated by Django 2.1.7 on 2019-04-12 17:50

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20190412_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='telefono',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
