# Generated by Django 2.1.7 on 2019-04-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20190412_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='idiomas',
            field=models.ManyToManyField(to='posts.Idioma'),
        ),
    ]
