# Generated by Django 2.1.7 on 2019-04-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_author_albun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='albun',
            new_name='imagen1',
        ),
        migrations.AddField(
            model_name='author',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='albun/'),
        ),
        migrations.AddField(
            model_name='author',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='albun/'),
        ),
        migrations.AddField(
            model_name='author',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='albun/'),
        ),
        migrations.AddField(
            model_name='author',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='albun/'),
        ),
        migrations.AddField(
            model_name='author',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to='albun/'),
        ),
        migrations.AddField(
            model_name='author',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='albun/'),
        ),
    ]
