# Generated by Django 2.1.7 on 2019-04-18 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20190418_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='imagen1',
            field=models.ImageField(default='default2.png', upload_to='albun/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
        migrations.AlterField(
            model_name='author',
            name='imagen2',
            field=models.ImageField(default='default2.png', upload_to='albun/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
        migrations.AlterField(
            model_name='author',
            name='imagen3',
            field=models.ImageField(default='default2.png', upload_to='albun/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
        migrations.AlterField(
            model_name='author',
            name='imagen4',
            field=models.ImageField(default='default2.png', upload_to='albun/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
        migrations.AlterField(
            model_name='author',
            name='imagen5',
            field=models.ImageField(default='default2.png', upload_to='albun/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
        migrations.AlterField(
            model_name='author',
            name='imagen6',
            field=models.ImageField(default='default2.png', upload_to='albun/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
        migrations.AlterField(
            model_name='author',
            name='portada',
            field=models.ImageField(default='default1.png', upload_to='portadas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
    ]
