# Generated by Django 2.1.7 on 2019-04-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20190418_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='imagen1',
            field=models.ImageField(default='default2.png', upload_to='albun/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='imagen2',
            field=models.ImageField(default='default2.png', upload_to='albun/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='imagen3',
            field=models.ImageField(default='default2.png', upload_to='albun/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='imagen4',
            field=models.ImageField(default='default2.png', upload_to='albun/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='imagen5',
            field=models.ImageField(default='default2.png', upload_to='albun/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='imagen6',
            field=models.ImageField(default='default2.png', upload_to='albun/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='portada',
            field=models.ImageField(default='default1.png', upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
